# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  # Dates
  - trigger: "`ds"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y%m%d"

  - trigger: "`dtn"
    replace: "{{mydate}}(sulrich)"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y%m%d"

  - trigger: "`:shrug:"
    replace: "¯\\_(ツ)_/¯"

  - trigger: "`>su"
    replace: ">> [sulrich]\n>>"

  - trigger: "`80-"
    replace: "--------------------------------------------------------------------------------"

  # - trigger: ""
  #   replace: ""

  # - trigger: ""
  #   replace: ""

  # - trigger: ""
  #   replace: ""

  - trigger: "`snipp"
    replace: "{ snipped - misc. previous correspondence }"

  - trigger: "`snips"
    replace: "{ snipped - misc. signatures }"

  - trigger: "`mgbug"
    replace: "[b/__bugid__](https://partnerissuetracker.corp.google.com/issues/__bugid__)"

  - trigger: "`gbug"
    replace: "https://partnerissuetracker.corp.google.com/issues/"

  - trigger: "`cclist"
    replace: "roland@arista.com, ssapa@arista.com, akshay@arista.com, akhilesh@arista.com, sriram@arista.com"

  - trigger: "`abug"
    replace: "https://bb/"

  - trigger: "`ains"
    replace: "### action items / next steps\n\n - [ ]"

  - trigger: "`zoom"
    replace: "{{zoom-invite}}"
    vars:
      - name: zoom-invite
        type: shell
        params:
          cmd: "cat '/Users/sulrich/.config/personal-zoom.txt'"
